### ISSUE TITLE
Add `Preview` of the `lat:long` via GMaps

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/geolocation#10]
# Current State : 

**_No method to preview the gathered `lat:long`_**

* +1 : **User is Blind**, if the data was correct or not.
* +2 : **User is Blind**, how precise the location was gathered.

# Expected State : 

**There should be !!**

## Are you assigned to this issue ?

**_Heck Ya!!_** :sunglasses:

**Comment by 0x48piraj** [comment]
Ping. @akshatnitd

**Comment by 0x48piraj** [comment]
Ping @Elgayar

**Comment by abishekvashok** [comment]
Looks cool go ahead
