### ISSUE TITLE
Integrate travis CI

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/geolocation#12]
Please add a `.travis.yml` and configure it, so that the tests pass.

**Comment by abishekvashok** [comment]
@akshatnitd it's a html project, why should we add a .travis.yml as no building is done here.

**Comment by akshatnitd** [comment]
Yes, right.
Then, in that case we need to remove this project from the Travis CI account

**Comment by abishekvashok** [comment]
@akshatnitd please do so, I have only write access no admin access.

**Comment by abishekvashok** [comment]
Closing as it is disabled now. Thanks
