### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/geolocation#18]
Improve Readme.md

- [ ] Add an image of geolocation.
- [ ] Add links.
![image](https://user-images.githubusercontent.com/33794760/48301834-f0b2e880-e519-11e8-899a-7849a695c5ff.png)
- [ ] Add how to use geolocation; now article hasn't  much details. 
![image](https://user-images.githubusercontent.com/33794760/48301873-95cdc100-e51a-11e8-9e64-d5468717b959.png)

I like to work on this.

@sk9331657 I would like if you review this issue before I am working on it.

**Comment by jakubpawlina** [comment]
I had done change before I had seen this issue, so I completed it now. I hope you don't mind it.
