### ISSUE TITLE
Display appropriate message when user blocks access to geolocation

### ISSUE THREAD

**Issue by hkumar0132** [fossasia/geolocation#29]
It's more user friendly if we show some message on the web page when the user blocks access to the geolocation

In the below image, it says 'Get geolocation again' when I block access.
![Screenshot (256)_LI](https://user-images.githubusercontent.com/63600554/122780319-608dd000-d2cc-11eb-9d1f-c4f06587c4dc.jpg)

A better thing to do would be to show a message like 'Unable to get geolocation. Please check if you have given access here'. 

* here would point to the settings page where they can allow access.

**Comment by hkumar0132** [comment]
Let me know if I can take on this issue, I am just getting started with open source.

**Comment by abishekvashok** [comment]
Hey,  thanks for your contribution, I appreciate for the amount of work you put in. However it appears unnecessary as this is not our focus right now. If you could divert your attention to open event, it would be really cool. Can you help us there?

**Comment by hkumar0132** [comment]
@abishekvashok Thank you for the response. I will try to contribute to open event.

**Comment by abishekvashok** [comment]
Closing this thereof
