### ISSUE TITLE
Add an api for the project

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/geolocation#5]
On calling a specific page it should be able to run the service which would make it to be used for other projects as well! 👍

**Comment by Elgayar** [comment]
Can you please elaborate more?

**Comment by Abhi2424shek** [comment]
Like calling a specific page returns the lat and lng of the user, the current project is used only for gci16.fossasia.org we should expand this to other projects as well, so we should have an api.

**Comment by abishekvashok** [comment]
Closing as this route map is not needed
